tables:
  - name: dab-mvp-dev.bronze.jc_citibike
    min_rows: 1

  - name: dab-mvp-dev.silver.jc_citibike
    min_rows: 1

  - name: dab-mvp-dev.gold.daily_ride_summary
    min_rows: 1

  - name: dab-mvp-dev.gold.daily_station_performance
    min_rows: 1

jobs:
  - name: "[dev amirout] dlt_pipeline"
    must_be_active: true

  - name: "[dev amirout] etl_pipeline_nb"
    must_be_active: true

  - name: "[dev amirout] etl_pipeline_py"
    must_be_active: true